

# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

sqlalchemy.url = postgresql://user:password@localhost:5432/s2c

# max length of characters to apply to the file template
truncate_slug_length = 80

# set to 'true' to run in "offline" mode (with no DB connection needed)
offline = true

# version table information
version_table = alembic_version
version_table_schema = public



